micronaut:
  application:
    name: postgresGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jps.defaut.properties.hibernate.hbm2ddl.auto: create-drop
